# Application

########## VISION ##########
# Project ID
#     https://www.customvision.ai/Select the Project, then the Settings Gear Icon
CUSTOM_VISION_PROJECT_ID:
CUSTOM_VISION_PROJECT_DIRECTION_ID:
# Iteration ID
#    https://www.customvision.ai/ Select the Project, then select performance
CUSTOM_VISION_ITERATION_ID:
CUSTOM_VISION_ITERATION_DIRECTION_ID:
# prediction
#    https://portal.azure.com -> Goto the Prediction Cognitive Services - Resrouce, then in Keys or Quickstart you can find the endpoint and key(S)
CUSTOM_VISION_ENDPOINT:
CUSTOM_VISION_PREDICTION_KEY:
# training
#    https://www.customvision.ai/ Select the Project, then select performance - training is on the right
CUSTOM_VISION_TRAINING_KEY:
CUSTOM_VISION_TRAINING_ENDPOINT:
CUSTOM_VISION_TRAINING_RESOURCEID:
TRAINING_FOLDER:

# testing
TESTING_FOLDER:
